const US_STATE = [
  { label: "Alabama", value: "AL" },
  { label: "Alaska", value: "AK" },
  { label: "Arizona", value: "AZ" },
  { label: "Arkansas", value: "AR" },
  { label: "California", value: "CA" },
  { label: "Colorado", value: "CO" },
  { label: "Connecticut", value: "CT" },
  { label: "Delaware", value: "DE" },
  { label: "District of Columbia", value: "DC" },
  { label: "Florida", value: "FL" },
  { label: "Georgia", value: "GA" },
  { label: "Hawaii", value: "HI" },
  { label: "Idaho", value: "ID" },
  { label: "Illinois", value: "IL" },
  { label: "Indiana", value: "IN" },
  { label: "Iowa", value: "IA" },
  { label: "Kansas", value: "KS" },
  { label: "Kentucky", value: "KY" },
  { label: "Louisiana", value: "LA" },
  { label: "Maine", value: "ME" },
  { label: "Maryland", value: "MD" },
  { label: "Massachusetts", value: "MA" },
  { label: "Michigan", value: "MI" },
  { label: "Minnesota", value: "MN" },
  { label: "Mississippi", value: "MS" },
  { label: "Missouri", value: "MO" },
  { label: "Montana", value: "MT" },
  { label: "Nebraska", value: "NE" },
  { label: "Nevada", value: "NV" },
  { label: "New Hampshire", value: "NH" },
  { label: "New Jersey", value: "NJ" },
  { label: "New Mexico", value: "NM" },
  { label: "New York", value: "NY" },
  { label: "North Carolina", value: "NC" },
  { label: "North Dakota", value: "ND" },
  { label: "Ohio", value: "OH" },
  { label: "Oklahoma", value: "OK" },
  { label: "Oregon", value: "OR" },
  { label: "Pennsylvania", value: "PA" },
  { label: "Rhode Island", value: "RI" },
  { label: "South Carolina", value: "SC" },
  { label: "South Dakota", value: "SD" },
  { label: "Tennessee", value: "TN" },
  { label: "Texas", value: "TX" },
  { label: "Utah", value: "UT" },
  { label: "Vermont", value: "VT" },
  { label: "Virginia", value: "VA" },
  { label: "Washington", value: "WA" },
  { label: "West Virginia", value: "WV" },
  { label: "Wisconsin", value: "WI" },
  { label: "Wyoming", value: "WY" },
];

const AUS_STATE = [
  { label: "New South Wales", value: "NSW" },
  { label: "Victoria", value: "VIC" },
  { label: "Queensland", value: "QLD" },
  { label: "Western Australia", value: "WA" },
  { label: "South Australia", value: "SA" },
  { label: "Tasmania", value: "TAS" },
  { label: "Australian Capital Territory", value: "ACT" },
  { label: "Northern Territory", value: "NT" },
];

const IND_PROVINCE = [
  { label: "Aceh", value: "Aceh" },
  { label: "Bali", value: "Bali" },
  { label: "Banten", value: "Banten" },
  { label: "Bengkulu", value: "Bengkulu" },
  { label: "Daerah Istimewa Yogyakarta", value: "Daerah Istimewa Yogyakarta" },
  { label: "DKI Jakarta", value: "DKI Jakarta" },
  { label: "Gorontalo", value: "Gorontalo" },
  { label: "Jambi", value: "Jambi" },
  { label: "Jawa Barat", value: "Jawa Barat" },
  { label: "Jawa Tengah", value: "Jawa Tengah" },
  { label: "Jawa Timur", value: "Jawa Timur" },
  { label: "Kalimantan Barat", value: "Kalimantan Barat" },
  { label: "Kalimantan Selatan", value: "Kalimantan Selatan" },
  { label: "Kalimantan Tengah", value: "Kalimantan Tengah" },
  { label: "Kalimantan Timur", value: "Kalimantan Timur" },
  { label: "Kalimantan Utara", value: "Kalimantan Utara" },
  { label: "Kepulauan Bangka Belitung", value: "Kepulauan Bangka Belitung" },
  { label: "Kepulauan Riau", value: "Kepulauan Riau" },
  { label: "Lampung", value: "Lampung" },
  { label: "Maluku", value: "Maluku" },
  { label: "Maluku Utara", value: "Maluku Utara" },
  { label: "Nusa Tenggara Barat", value: "Nusa Tenggara Barat" },
  { label: "Nusa Tenggara Timur", value: "Nusa Tenggara Timur" },
  { label: "Papua", value: "Papua" },
  { label: "Papua Barat", value: "Papua Barat" },
  { label: "Papua Barat Daya", value: "Papua Barat Daya" },
  { label: "Papua Pegunungan", value: "Papua Pegunungan" },
  { label: "Papua Selatan", value: "Papua Selatan" },
  { label: "Papua Tengah", value: "Papua Tengah" },
  { label: "Riau", value: "Riau" },
  { label: "Sulawesi Barat", value: "Sulawesi Barat" },
  { label: "Sulawesi Selatan", value: "Sulawesi Selatan" },
  { label: "Sulawesi Tengah", value: "Sulawesi Tengah" },
  { label: "Sulawesi Tenggara", value: "Sulawesi Tenggara" },
  { label: "Sulawesi Utara", value: "Sulawesi Utara" },
  { label: "Sumatera Barat", value: "Sumatera Barat" },
  { label: "Sumatera Selatan", value: "Sumatera Selatan" },
  { label: "Sumatera Utara", value: "Sumatera Utara" },
];

export const countries = [
  {
    id: "USA",
    name: "United States",
    fields: [
      {
        key: "us_address_1",
        name: "addressLine1",
        label: "Address Line 1",
        type: "text",
        placeholder: "123 Main Street",
        required: true,
      },
      {
        key: "us_address_2",
        name: "addressLine2",
        label: "Address Line 2",
        type: "text",
        placeholder: "123 Main Street",
        required: false,
      },
      {
        key: "us_city",
        name: "city",
        label: "City",
        type: "text",
        placeholder: "New York",
        required: true,
      },
      {
        key: "us_region",
        name: "region",
        label: "State",
        type: "select",
        required: true,
        placeholder: "Select a state",
        options: US_STATE,
      },
      {
        key: "us_postal_code",
        name: "postalCode",
        label: "ZIP Code",
        type: "text",
        placeholder: "10001",
        required: true,
      },
    ],
  },
  {
    id: "AUS",
    name: "Australia",
    fields: [
      {
        key: "au_address_1",
        name: "addressLine1",
        label: "Address Line 1",
        type: "text",
        placeholder: "123 Main Street",
        required: true,
      },
      {
        key: "au_address_1",
        name: "addressLine2",
        label: "Address Line 2",
        type: "text",
        placeholder: "123 Main Street",
        required: false,
      },
      {
        key: "au_suburb",
        name: "suburb",
        label: "Suburb",
        type: "text",
        placeholder: "Sydney",
        required: true,
      },
      {
        key: "au_region",
        name: "region",
        label: "State/Territory",
        type: "select",
        required: true,
        placeholder: "Victoria",
        options: AUS_STATE,
      },
      {
        key: "au_postal_code",
        name: "postalCode",
        label: "Postcode",
        type: "text",
        placeholder: "2000",
        required: true,
      },
    ],
  },
  {
    id: "IDN",
    name: "Indonesia",
    fields: [
      {
        key: "id_address_1",
        name: "addressLine1",
        label: "Jalan (Street Address)",
        type: "text",
        placeholder: "Jalan Merdeka 123",
        required: true,
      },
      {
        key: "id_village",
        name: "village",
        label: "Kelurahan/Desa (Village)",
        type: "text",
        placeholder: "Cikini",
        required: false,
      },
      {
        key: "id_district",
        name: "district",
        label: "Kecamatan (District)",
        type: "text",
        placeholder: "Menteng",
        required: true,
      },
      {
        key: "id_city",
        name: "city",
        label: "Kota/Kabupaten (City / Regency)",
        type: "text",
        placeholder: "Jakarta Pusat",
        required: true,
      },
      {
        key: "id_region",
        name: "region",
        label: "Provinsi (Province)",
        type: "select",
        placeholder: "DKI Jakarta",
        required: true,
        options: IND_PROVINCE,
      },
      {
        key: "id_postal_code",
        name: "postalCode",
        label: "Kode Pos (Postal Code)",
        type: "text",
        placeholder: "10110",
        required: true,
      },
    ],
  },
];

export function getCountryConfig(countryId) {
  return countries.find((c) => c.id === countryId);
}

export const API_URL = import.meta.env.VITE_API_BASE_URL;
